### ISSUE TITLE
ensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3] = 151 is not in [0, 10)

### ISSUE THREAD

**Issue by c1a1o1** [KunZhou9646/Singing-Voice-Conversion-with-conditional-VAW-GAN#4]
ensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3] = 151 is not in [0, 10)
	 [[{{node Generator_3/embedding_lookup_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\supervisor.py", line 1004, in managed_session
    yield sess
  File "F:\work\Singing-Voice-Conversion-with-conditional-VAW-GAN-master\codes\trainer\vawgan.py", line 106, in train
    results = sess.run(fetches, feed_dict=feed_dict)
  File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py",

**Comment by c1a1o1** [comment]
def _generator(self, z, y, f, is_training):
        ''' In this version, we only generate the target, so `y` is useless '''
        subnet = self.arch['generator']
        n_layer = len(subnet['output'])
        h, w, c = subnet['hwc']

        y = tf.nn.embedding_lookup(self.y_emb, y)
        f = tf.nn.embedding_lookup(self.f_emb, f)

**Comment by 980202006** [comment]
Hi, the f is the F0. So it should use  another paramter for its layer, instead of self.arch['y_dim']., which  is mentioned in line 25.

**Comment by 980202006** [comment]
Additionly, the f0 uses embedding layer to merge to the model. It may be a problem, when the f0 value not in training dataset. The f0 is hz range, this problem very well could happen.
